import tkinter.messagebox as messagebox
import tkinter as tk
from tkinter.constants import SUNKEN
cal = tk.Tk()
cal.title("Calculator")

frame = tk.Frame(master=cal, bg="white", padx=20)
frame.pack()
entry = tk.Entry(master=frame, width=30, borderwidth=5, relief=SUNKEN)
entry.grid(row=0, column=0, columnspan=3, padx=10, pady=10)
def button_click(number):
    entry.insert(tk.END, number)
def result():
    try:
        y = str(eval(entry.get()))
        entry.delete(0,tk.END)  
        entry.insert(0,y)
    except:
        tkinter.messagebox.showinfo("Error", "Invalid Input")
def clear():
    entry.delete(0, tk.END)
    
button_1 = tk.Button(master=frame, text="1", padx=15, pady=5, command=lambda: button_click(1))
button_2 = tk.Button(master=frame, text="2",padx=15, pady=5, command=lambda: button_click(2))
button_3 = tk.Button(master=frame, text="3", padx=15, pady=5, command=lambda: button_click(3))
button_4 = tk.Button(master=frame, text="4", padx=15, pady=5, command=lambda: button_click(4)) 
button_5 = tk.Button(master=frame, text="5", padx=15, pady=5, command=lambda: button_click(5))
button_6 = tk.Button(master=frame, text="6", padx=15, pady=5, command=lambda: button_click(6))
button_7 = tk.Button(master=frame, text="7",padx=15, pady=5, command=lambda: button_click(7)) 
button_8 = tk.Button(master=frame, text="8", padx=15, pady=5, command=lambda: button_click(8))
button_9 = tk.Button(master=frame, text="9", padx=15, pady=5, command=lambda: button_click(9))
button_0 = tk.Button(master=frame, text="0", padx=15, pady=5, command=lambda: button_click(0))
button_00 = tk.Button(master=frame, text="00", padx=15, pady=5, command=lambda: button_click(00))
button_dot = tk.Button(master=frame, text=".", padx=15, pady=5, command=lambda: button_click("."))
button_add = tk.Button(master=frame, text="+", padx=15, pady=5, command=lambda: button_click("+"))
button_subtract = tk.Button(master=frame, text="-", padx=15, pady=5, command=lambda: button_click("-"))    
button_multiply = tk.Button(master=frame, text="*", padx=15, pady=5, command=lambda: button_click("*"))
button_divide = tk.Button(master=frame, text="/", padx=15, pady=5, command=lambda: button_click("/"))
button_equal = tk.Button(master=frame, text="=", padx=15, pady=5, width=30, command=result)
button_clear = tk.Button(master=frame, text="Clear", padx=15, pady=5, width=30,command=clear)
button_add.grid(row=1, column=3, pady=2)
button_subtract.grid(row=2, column=3, pady=2)
button_multiply.grid(row=3, column=3, pady=2)
button_divide.grid(row=4, column=3, pady=2)
button_equal.grid(row=7, column=0, columnspan=4, pady=2)
button_clear.grid(row=6, column=0, columnspan=4, pady=2)
button_1.grid(row=3, column=0, pady=2)
button_2.grid(row=3, column=1, pady=2)
button_3.grid(row=3, column=2, pady=2)
button_4.grid(row=2, column=0, pady=2)
button_5.grid(row=2, column=1, pady=2)
button_6.grid(row=2, column=2, pady=2)
button_7.grid(row=1, column=0, pady=2)
button_8.grid(row=1, column=1, pady=2)
button_9.grid(row=1, column=2, pady=2)
button_0.grid(row=4, column=0, pady=2)
button_00.grid(row=4, column=1, pady=2)
button_dot.grid(row=4,column=2, pady=2)
cal.mainloop()